version: "3.7"
services:
  db:
    image: "postgres:11-alpine"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rabbithole
    ports:
      - 5432:5432
  rabbit:
    image: "rabbitmq:3.7"
    environment:
      - RABBITMQ_DEFAULT_VHOST=esa_dev
    ports:
      - 5672:5672 