version: "3.7"
services:
  db:
    image: "postgres:11-alpine"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rabbithole
    ports:
      - 5432:5432
  rabbit:
    image: "rabbitmq:3.7"
    environment:
      - RABBITMQ_DEFAULT_VHOST=esa_dev
    ports:
      - 5672:5672
  app:
    image: "rabbithole"
    build: .
    depends_on:
      - db
      - rabbit
    environment:
      - RABBITHOLE_Logging__LogLevel__Default=Debug
      - RABBITHOLE_RabbitMQ__HostName=rabbit
      - RABBITHOLE_ConnectionStrings__Events=User ID=postgres;Password=password;Host=db;Port=5432;Database=rabbithole